// <auto-generated />
using System;
using CineMania.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CineMania.Migrations
{
    [DbContext(typeof(CinemaniaContext))]
    [Migration("20210911143648_nono")]
    partial class nono
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("CineMania.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CineMania.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.",
                            Genre = "Action",
                            ImageName = "black_widow.jpg",
                            ReleaseDate = new DateTime(2021, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Widow"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A family man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
                            Genre = "Sci-Fi",
                            ImageName = "the_tomorrow_war.jpg",
                            ReleaseDate = new DateTime(2021, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Tomorrow War"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Beca, a freshman at Barden University, is cajoled into joining The Bellas, her school's all-girls singing group. Injecting some much needed energy into their repertoire, The Bellas take on their male rivals in a campus competition",
                            Genre = "Comedy",
                            ImageName = "black_widow.jpg",
                            ReleaseDate = new DateTime(2013, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pitch Perfect"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A family falls victim to a group of mutated cannibals in a desert far away from civilization.",
                            Genre = "Horror",
                            ImageName = "hills_have_eyes.jpg",
                            ReleaseDate = new DateTime(2006, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hills Have Eyes"
                        },
                        new
                        {
                            Id = 5,
                            Description = "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway",
                            Genre = "Animation",
                            ImageName = "up.jpg",
                            ReleaseDate = new DateTime(2009, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Up"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Genre = "Crime",
                            ImageName = "pulp_fiction.jpg",
                            ReleaseDate = new DateTime(1994, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A small-time boxer gets a supremely rare chance to fight a heavyweight champion in a bout in which he strives to go the distance for his self-respect.",
                            Genre = "Drama",
                            ImageName = "rocky.jpg",
                            ReleaseDate = new DateTime(1976, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Evil Dead is a 1981 American supernatural horror film written and directed by Sam Raimi, ... The film's high-definition debut was in a 2010 Blu-ray",
                            Genre = "action",
                            ImageName = "image.jpg",
                            ReleaseDate = new DateTime(2014, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "evildead"
                        },
                        new
                        {
                            Id = 9,
                            Description = "hrithicshan  is the indian movies played by tiger sinopf and prity girl, drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
                            Genre = "romantic",
                            ImageName = "image1.jpg",
                            ReleaseDate = new DateTime(2020, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "hrithicshan"
                        },
                        new
                        {
                            Id = 10,
                            Description = "For many scholars, Revelation 1:14-15 offers a clue that Jesus's skin was a darker hue and that his hair was woolly in texture. The hairs of his head, it says, were white as white wool, white as snow",
                            Genre = "drama",
                            ImageName = "image2.jpg",
                            ReleaseDate = new DateTime(2015, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "jesus"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Kya Kehna (English: So well Said) is a 2000 Indian Hindi romantic drama film. ... Kya Kehna dealt with the taboo issue of pre-marital pregnancy and society views ",
                            Genre = "hollow",
                            ImageName = "image3.jpg",
                            ReleaseDate = new DateTime(1998, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "kykehna"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A highly decorated ex-Marine sniper returns to action to foil an assassination plot targeting the president, but soon finds himself framed for murder.",
                            Genre = "action",
                            ImageName = "image4.jpg",
                            ReleaseDate = new DateTime(2010, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "shooter"
                        },
                        new
                        {
                            Id = 13,
                            Description = "is a 2017 Philippine melodrama television series starring Beauty Gonzalez, ... ABS-CBN television drama filmed in high, is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
                            Genre = "romantic",
                            ImageName = "image5.jpg",
                            ReleaseDate = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "pusongligaw"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Crocodiles have powerful jaws with many conical teeth and short legs with clawed webbed toes. They share a unique body form that allows the eyes, ears, and nostrils to be above the water surface while mos.",
                            Genre = "drama",
                            ImageName = "image7.jpg",
                            ReleaseDate = new DateTime(2011, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "crocodile"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Superman is a fictional character and a superhero who first appeared in American comic books published by DC Comics. ... He was found and adopted by farmers ",
                            Genre = "catoon",
                            ImageName = "image8.jpg",
                            ReleaseDate = new DateTime(1899, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "superman"
                        },
                        new
                        {
                            Id = 16,
                            Description = "redemption a man from united state who fight with a thousand and thousand people ,is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
                            Genre = "action",
                            ImageName = "up.jpg",
                            ReleaseDate = new DateTime(2000, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "anaconda"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Zombies are the main antagonists of the World War Z franchise. They are the reanimated corpses of dead humans andare extremely violent beings that attack anything living to eat, kill, and infect..",
                            Genre = "action",
                            ImageName = "image9.jpg",
                            ReleaseDate = new DateTime(2021, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "war"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
